require('sauce.general')
require('sauce.keybinds')
require('sauce.plugins')
require('sauce.lsp')
require('sauce.treesitter')
require('sauce.nvim-autopairs')
require('sauce.comment')
require('sauce.nvim-cmp')
require('sauce.telescope')
require('sauce.nvim-tree')
require('sauce.lualine')
require('sauce.bufferline')
require('sauce.whichkey')
require('sauce.alpha')
require('sauce.impatient')
vim.cmd('colorscheme onedarker')
